# Generated by Django 5.0.1 on 2024-01-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
